version: '2.1'
services:
  postgres:
    image: postgis/postgis:10-2.5-alpine
    volumes:
      - ./databases/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"